### ISSUE TITLE
Database import error

### ISSUE THREAD

**Issue by Yeet0420** [Catover203/GeometryDashPrivateServer#11]
When i import `database.sql` it give a lot of errors

**Comment by Catover203** [comment]
What is error?
send me scereenshot

**Comment by Catover203** [comment]
@Yeet0402 if this not work, flow this step:

Needed: phpmyadmin

go to your gdps database and go to sql
copy all text at http://catboom.ml/database.txt
paste at your gdps sql
done...

**Comment by Catover203** [comment]
I fixed, now you can download again.
